---
title: "reconstruct_trait_simu"
author: "Rémi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(NetworkEnvGradGeneration)
library(ade4)
library(igraph)
```


```{r}
##################################################"
## reconst.coa reconstitue le tableau original Nij
## ici on reconstitue les ecarts entre pij observé et théorique pi.p.j
## (pij - pi.p.j) pour reconst_afc ou normés par le chi2 ((pij - pi.p.j)/pi.p.j)) pour reconst_afc2
##################################################"

library(ade4)

reconst_afc <- function (dudi, nf = 1, ...) 
{
    ## reconst (pij - pi.p.j)/pi.p.j
    if (!inherits(dudi, "dudi")) 
        stop("Object of class 'dudi' expected")
    if (nf > dudi$nf) 
        stop(paste(nf, "factors need >", dudi$nf, "factors available\n"))
    if (!inherits(dudi, "coa")) 
        stop("Object of class 'dudi' expected")
    pl <- dudi$lw
    pc <- dudi$cw
    n <- dudi$N
    #res0 <- outer(pl, pc) * n
    res0 <- matrix(1, length(pl), length(pc)) # c'est bien pc?
    res <- data.frame(res0-1) # pourquoi pas direct matr(0, pl,pc)?
    names(res) <- names(dudi$tab) # col.names?
    row.names(res) <- row.names(dudi$tab)
    #res0 <- outer(pl, pc) * n
    if (nf == 0) 
        return(res)
    for (i in 1:nf) {
        xli <- dudi$li[, i]
        yc1 <- dudi$c1[, i] # pourquoi li et C1 et pas l1/c1, ou li/co? 
        res <- res + outer(xli, yc1) * res0
    }
    return(res)
} 


reconst_afc2 <- function (dudi, nf = 1, ...) 
{
    ## reconst (pij - pi.p.j)
    if (!inherits(dudi, "dudi")) 
        stop("Object of class 'dudi' expected")
    if (nf > dudi$nf) 
        stop(paste(nf, "factors need >", dudi$nf, "factors available\n"))
    if (!inherits(dudi, "coa")) 
        stop("Object of class 'dudi' expected")
    pl <- dudi$lw
    pc <- dudi$cw
    n <- dudi$N
    res0 <- outer(pl, pc) * n
    res <- data.frame(res0 - 1)
    names(res) <- names(dudi$tab)
    row.names(res) <- row.names(dudi$tab)
    if (nf == 0) 
        return(res)
    for (i in 1:nf) {
        xli <- dudi$li[, i]
        yc1 <- dudi$c1[, i]
        res <- res + outer(xli, yc1) * res0
    }
    return(res)
}
```

# Generate Network

```{r}
nb_frame = 16
spe_resource = 70
spe_consumer = 200
simulated_network <- env_grad_netw(nb_resource = spe_resource , nb_consumer = spe_consumer,
                                   nb_location = nb_frame,
                                   know_env_grad_pos = F, ninter = 1400, 
                                   mean_tol = 0.2, sd_tol = 0.2,
                                   mean_tol_env = 0.2, sd_tol_env = 0.3,
                                   delta = 1, corr_env_trait = 0)

```


## Extract the giant component

### Extract the components that are not always part of the giant component

```{r}
connected_compo <- function(simu_netw, nb_frame){
  not_always_con <- c()
  sampled_netw <- Reduce('+', simulated_network$obs_network)
  sampled_netw_con = sampled_netw[which(rowSums(sampled_netw) != 0), which(colSums(sampled_netw) != 0)]
  component <- igraph::components(graph_from_incidence_matrix(sampled_netw_con))
  if (length(component$csize) != 1) {
      not_always_con <- c(not_always_con, names(component$membership[which(component$membership != which.max(component$csize))]))
  }
  
  print(paste(length(unique(not_always_con))/(spe_consumer + spe_resource) * 100,"% of the species will be removed because there is some frames where they are not part of the giant component"))
  return(unique(not_always_con))
}
sampled_netw
not_giant_compo <- connected_compo(simulated_network, nb_frame)
```

```{r}
filter_giant_component <- function(simu_netw, not_giant_compo){
  # On observed data
  simu_netw$obs_giant_compo <- lapply(simu_netw$obs_network, function(arr){
    arr[!dimnames(arr)[[1]] %in% unique(not_giant_compo),
        !dimnames(arr)[[2]] %in% unique(not_giant_compo)]
  })
  
  # On the trait matching matrix
  simu_netw$trait$trait_mat_giant_compo <- simu_netw$trait$matching_matrix[!dimnames(simu_netw$obs_network[[1]])[[1]] %in% unique(not_giant_compo),
                                                                                !dimnames(simu_netw$obs_network[[1]])[[2]] %in% unique(not_giant_compo)]
  
  # On the resource traits
  simu_netw$trait$resource_giant_compo <- simu_netw$trait$trait_resource[!dimnames(simu_netw$trait$trait_resource)[[1]] %in% unique(not_giant_compo),]
  
  #On the consumer traits
  simu_netw$trait$consumer_giant_compo <- simu_netw$trait$trait_consumer[!dimnames(simu_netw$trait$trait_consumer)[[1]] %in% unique(not_giant_compo),,]
  
  return(simu_netw)
}

simulated_network <- filter_giant_component(simulated_network, not_giant_compo)

# not_giant_compo
# simulated_network$trait$trait_mat_giant_compo

```


```{r}
ade4::table.value(simulated_network$obs_giant_compo[[1]])
```

```{r}
sampled_netw <- Reduce('+', simulated_network$obs_giant_compo)
# to keep only the connected species
sampled_netw_con <- sampled_netw[which(rowSums(sampled_netw) != 0), which(colSums(sampled_netw) != 0)]
component <- igraph::components(graph_from_incidence_matrix(sampled_netw_con))
if (length(component$csize) != 1) {
  print(paste("The network",i, "is not strongly connected, there is", component$no, "connected components"))
  print(names(component$membership[which(component$membership != which.max(component$csize))]))
  print("are not part of of the giant component.")
  not_always_con <- c(not_always_con, names(component$membership[which(component$membership != which.max(component$csize))]))
}
table.value(sampled_netw)

plot(graph_from_incidence_matrix(sampled_netw), vertex.size=5)
```

```{r}
degree(graph_from_incidence_matrix(sampled_netw))
```


```{r}
tab = Reduce('+', simulated_network$obs_giant_compo) # afin de générer le réseau moyen

afc.tab=dudi.coa(tab, nf = 18, scannf = FALSE)

par(mfrow=c(2,2))
ade4::table.value(simulated_network$trait$trait_mat_giant_compo, x = rank(afc.tab$co[,1]), y = rank(afc.tab$li[,1]), csize = 0.8) # trait matching matrix et tri selon le premier axe
ade4::table.value(tab, x = rank(afc.tab$co[,1]), y = rank(afc.tab$li[,1])) # réseau moyen observé
toto = reconst_afc(afc.tab, nf = 8) # pour reconstruire le réseau moyen à partir des positions sur l'AFC mais on voudrait plustôt obtenir le trait matching
ade4::table.value(toto, x = rank(afc.tab$co[,1]), y = rank(afc.tab$li[,1]), csize = 0.8) # plot le réseau reconstruit
ade4::table.value(afc.tab$tab, x = rank(afc.tab$co[,1]), y = rank(afc.tab$li[,1])) # transformed average table
```



```{r}
# afc.tab$li

cor(simulated_network$trait$resource_giant_compo, afc.tab$li) # resource correlation with the rows of the CA depending on the axis
cor(simulated_network$trait$consumer_giant_compo[,1,], afc.tab$co) # consumer correlation with the columns of the CA depending on the axis
```

```{r}
scatter(afc.tab)
```


```{r}
library(adegraphics)
adegraphics::table.value(afc.tab$tab, coordsx = rank(afc.tab$co[,1]), coordsy  = rank(afc.tab$li[,1]), method = "color", ppoint.cex = 0.2) # transformed average table

image(simulated_network$trait$matching_matrix [order(afc.tab$li[,1]), order(afc.tab$co[,1])])

```


```{r}
tr1x1_line <- c()
tr1x2_line <- c()
tr1x3_line <- c()
tr1x4_line <- c()

tr2x1_line <- c()
tr2x2_line <- c()
tr2x3_line <- c()
tr2x4_line <- c()

tr1x1_col <- c()
tr1x2_col <- c()
tr1x3_col <- c()
tr1x4_col <- c()

tr2x1_col <- c()
tr2x2_col <- c()
tr2x3_col <- c()
tr2x4_col <- c()

for (i in 1:5) {
  nb_frame = 5
  spe_resource = 50
  spe_consumer = 100
  simulated_network <- env_grad_netw(nb_resource = spe_resource , nb_consumer = spe_consumer,
                                     nb_location = nb_frame,
                                     know_env_grad_pos = F, ninter = 100, 
                                     mean_tol = 0.1, sd_tol = 0.1,
                                     mean_tol_env = 0.1, sd_tol_env = 0.1,
                                     delta = 1, corr_env_trait = 0,
                                     ratio_grad = 0.6)
  
  not_giant_compo <- connected_compo(simulated_network, nb_frame)
  simulated_network <- filter_giant_component(simulated_network, not_giant_compo)
  
  
  tab = Reduce('+', simulated_network$obs_giant_compo) # afin de générer le réseau moyen
  afc.tab=dudi.coa(tab, nf = 18, scannf = FALSE)
  
  (corr_line <- cor(simulated_network$trait$resource_giant_compo, afc.tab$li)) # resource correlation with the rows of the CA depending on the axis
  (corr_col <- cor(simulated_network$trait$consumer_giant_compo[,1,], afc.tab$co)) # consumer correlation with the columns of the CA depending on the axis
  
  tr1x1_line <- c(tr1x1_line, abs(corr_line[1,1]))
  tr1x2_line <- c(tr1x2_line, abs(corr_line[1,2]))
  tr1x3_line <- c(tr1x3_line, abs(corr_line[1,3]))
  tr1x4_line <- c(tr1x4_line, abs(corr_line[1,4]))
  
  tr2x1_line <- c(tr2x1_line, abs(corr_line[2,1]))
  tr2x2_line <- c(tr2x2_line, abs(corr_line[2,2]))
  tr2x3_line <- c(tr2x3_line, abs(corr_line[2,3]))
  tr2x4_line <- c(tr2x4_line, abs(corr_line[2,4]))

  tr1x1_col <- c(tr1x1_col, abs(corr_col[1,1]))
  tr1x2_col <- c(tr1x2_col, abs(corr_col[1,2]))
  tr1x3_col <- c(tr1x3_col, abs(corr_col[1,3]))
  tr1x4_col <- c(tr1x4_col, abs(corr_col[1,4]))
  
  tr2x1_col <- c(tr2x1_col, abs(corr_col[2,1]))
  tr2x2_col <- c(tr2x2_col, abs(corr_col[2,2]))
  tr2x3_col <- c(tr2x3_col, abs(corr_col[2,3]))
  tr2x4_col <- c(tr2x4_col, abs(corr_col[2,4]))
  
  s.corcircle(corr_line)
  s.corcircle(corr_col)
  scatter(afc.tab)
}
# par(mfrow = c(2,1))
boxplot(tr1x1_line, tr1x2_line, tr1x3_line, tr1x4_line, names = c("Tr1 axe1", "Tr1 axe2", "Tr1 axe3", "Tr1 axe4"), main = "Correlation between trait 1 and axes for line species (res)", ylim = c(0,1))
boxplot(tr1x1_line, tr2x2_line, tr2x3_line, tr2x4_line, names = c("Tr2 axe1", "Tr2 axe2", "Tr2 axe3", "Tr2 axe4"), main = "Correlation between trait 2 and axes for line species (res)", ylim = c(0,1))

boxplot(tr1x1_col, tr1x2_col, tr1x3_col, tr1x4_col, names = c("Tr1 axe1", "Tr1 axe2", "Tr1 axe3", "Tr1 axe4"), main = "Correlation between trait 1 and axes for column species (con)", ylim = c(0,1))
boxplot(tr1x1_col, tr2x2_col, tr2x3_col, tr2x4_col, names = c("Tr2 axe1", "Tr2 axe2", "Tr2 axe3", "Tr2 axe4"), main = "Correlation between trait 2 and axes for column species (con)", ylim = c(0,1))

```

```{r}
s.corcircle(cor(simulated_network$trait$resource_giant_compo, afc.tab$li))
```


```{r}
# detach("package:adegraphics", unload = TRUE)
if(!adegraphicsLoaded()) {
  data (olympic)
  dudi1 <- dudi.pca(olympic$tab, scan = FALSE) # a normed PCA
  par(mfrow = c(2, 2))
  s.corcircle(dudi1$co, lab = names(olympic$tab))
  s.corcircle(dudi1$co, cgrid = 0, full = FALSE, clab = 0.8)
  s.corcircle(dudi1$co, lab = as.character(1:11), cgrid = 2,
    full = FALSE, sub = "Correlation circle", csub = 2.5,
    possub = "bottomleft", box = TRUE)
  s.arrow(dudi1$co, clab = 1)
  par(mfrow = c(1, 1))
}
```

# Take care of the weird axes

```{r}
nb_frame = 5
spe_resource = 50
spe_consumer = 50
simulated_network <- env_grad_netw(nb_resource = spe_resource , nb_consumer = spe_consumer,
                                   nb_location = nb_frame,
                                   know_env_grad_pos = F, ninter = 500, 
                                   mean_tol = 0.1, sd_tol = 0.1,
                                   mean_tol_env = 0.1, sd_tol_env = 0.1,
                                   delta = 1, corr_env_trait = 0,
                                   ratio_grad = 0.7)

not_giant_compo <- connected_compo(simulated_network, nb_frame)
simulated_network <- filter_giant_component(simulated_network, not_giant_compo)


tab = Reduce('+', simulated_network$obs_giant_compo) # afin de générer le réseau moyen
afc.tab=dudi.coa(tab, nf = 18, scannf = FALSE)

(corr_line <- cor(simulated_network$trait$resource_giant_compo, afc.tab$li)) # resource correlation with the rows of the CA depending on the axis
(corr_col <- cor(simulated_network$trait$consumer_giant_compo[,1,], afc.tab$co)) # consumer correlation with the columns of the CA depending on the axis

s.corcircle(corr_line)
s.corcircle(corr_col)
ade4::table.value(tab, clegend = 0)
scatter(afc.tab)

plot(graph_from_incidence_matrix(tab[rowSums(tab) != 0, colSums(tab) != 0]), vertex.size=5)

simulated_network

fou1 = foucart(lapply(simulated_network$obs_giant_compo, as.data.frame), scannf = F, nf = 2)
plot(fou1)
```

