---
title: "Test kolmogorov"
author:
  - name: "Rémi Legrand"
abstract: >
  Try if 
date: "`r format(Sys.time(), '%d %B %Y')`"
url: https://GitHubID.github.io/Repository/
github-repo: GitHubID/Repository
# Language
lang: en-US
otherlangs: [fr-FR,it]
# Bibliography
bibliography: references.bib
biblio-style: chicago
# LaTeX
preamble: >
  \hyphenation{bio-di-ver-si-ty sap-lings}
# Print table of contents in PDFs?
pdftoc: false
# If true, choose its depth
toc-depth: 3
# URL color
urlcolor: blue
# Do not modify
always_allow_html: yes
csquotes: true
output:
  bookdown::html_document2:
    toc: yes
    toc_float: yes
    css: style.css
    code_folding: show
  rmdformats::downcute:
    use_bookdown: yes
    lightbox: yes
  bookdown::gitbook:
    config:
      download: "pdf"
      sharing:
        github: yes
  bookdown::pdf_book:
    template: latex/template.tex
    citation_package: natbib
    latex_engine: xelatex
    keep_tex: yes
  bookdown::word_document2: default
---

# Kolmogorov on a normal law

Try out with dummy data to check how well it works

```{r}
pval = c()

for (i in 1:1000) {
  sample_coord <- c(rnorm(10, 0, 0.1), rnorm(5, 1, 0.1))
  test = ks.test(sample_coord, "pnorm", mean = mean(sample_coord), sd = sd(sample_coord), simulate.p.value = T)
  pval = c(pval, test$p.value)
}


qqnorm(sample_coord)

hist(pval)
abline(v = median(pval), col = "red")

```

```{r}
pnorm(1)
```

# Try with multivariate normal law

In our case, 

```{r}
library(MASS)
```

```{r}
# mvrnorm(n = 2, mu = c(0,0,0), Sigma = c(1,1,1))

Sigma <- matrix(c(10,3,3,2),2,2)
Sigma
var(mvrnorm(n = 1000, rep(0, 2), Sigma))
var(mvrnorm(n = 1000, rep(0, 2), Sigma, empirical = TRUE))


```

```{r}
Sigma <- matrix(c(10,0,0,2),2,2)
dummy_coord <- mvrnorm(n = 1000, rep(0, 2), Sigma)
plot(x = dummy_coord[,1], y = dummy_coord[,2])
```

